# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
version: 3.0.3
permalink: pretty

# Build settings
markdown: kramdown

collections:
  business-finance:
    output: true
  business-insurance:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "Business Finance"
    values:
      layout: "business-finance"
  -
    scope:
      path: ""
      type: "Business Insurance"
    values:
      layout: "business-insurance"      